#!/bin/sh

bundle exec jekyll build

echo "daemon off;                                      " >> /tmp/nginx.conf
echo "worker_processes 1;                              " >> /tmp/nginx.conf
echo "pid /run/nginx.pid;                              " >> /tmp/nginx.conf
echo "error_log /dev/stdout info;                      " >> /tmp/nginx.conf
echo "events {                                         " >> /tmp/nginx.conf
echo "    worker_connections  1024;                    " >> /tmp/nginx.conf
echo "}                                                " >> /tmp/nginx.conf
echo "http {                                           " >> /tmp/nginx.conf
echo "  include /etc/nginx/mime.types;                 " >> /tmp/nginx.conf
echo "  server {                                       " >> /tmp/nginx.conf
echo "    gzip on;                                     " >> /tmp/nginx.conf
echo "    gzip_http_version 1.1;                       " >> /tmp/nginx.conf
echo "    gzip_comp_level 2;                           " >> /tmp/nginx.conf
echo "    gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css;" >> /tmp/nginx.conf
echo "    listen 0.0.0.0:80;                           " >> /tmp/nginx.conf
echo "    access_log /dev/stdout;                      " >> /tmp/nginx.conf
echo "    location / {                                 " >> /tmp/nginx.conf
echo "      root  /app/_site;                          " >> /tmp/nginx.conf
echo "    }                                            " >> /tmp/nginx.conf
echo "  }                                              " >> /tmp/nginx.conf
echo "} " >> /tmp/nginx.conf

nginx -c /tmp/nginx.conf
